

export const SESSION_LOGIN = "SESSION_LOGIN";
export const SESSION_LOGOUT = "SESSION_LOGOUT";
export const SESSION_MESSAGE = "SESSION_MESSAGE";
export const SESSION_MESSAGE_REMOVE = "SESSION_MESSAGE_REMOVE";
export const ADVANCED_MODE_TOGGLE = "ADVANCED_MODE_TOGGLE";

